---
namespace: arvatosystems
name: ansible_oracle
description: "Impoartant! This is a beta release! This is a fork of the collection of ansible-oracle from https://github.com/oravirt/ansible-oracle"
version: 0.0.1
repository: https://github.com/moer020/ansible-oracle.git
readme: README.md
authors:
  - Marvin Mörking
license:
  - "MIT"
tags:
  - database
  - infrastructure
  - oracle
dependencies:
  community.general: '>=7.0.0'
  devsec.hardening: 8.6.0
