---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml

- name: ansible-oracle Collection version
  ansible.builtin.debug:
    msg: "ansible-oracle version: {{ lookup('community.general.collection_version', 'arvatosystems.ansible_oracle') }}"
