---

- name: Create Golden-Images for Oracle Database, Oracle Restart
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - arvatosystems.ansible_oracle.oraswdb_golden_image
    - arvatosystems.ansible_oracle.oraswgi_golden_image
