---

- name: Database Server Patching
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - arvatosystems.ansible_oracle.oraswdb_manage_patches
    - arvatosystems.ansible_oracle.oradb_datapatch
