---

- name: Host configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - arvatosystems.ansible_oracle.common
    - arvatosystems.ansible_oracle.orahost
    - arvatosystems.ansible_oracle.orahost_storage
    - arvatosystems.ansible_oracle.orahost_ssh
    - arvatosystems.ansible_oracle.cxoracle
    - arvatosystems.ansible_oracle.orahost_logrotate

  post_tasks:
    - name: Restart autofs
      ansible.builtin.service:
        name: autofs
        enabled: true
        state: restarted
      tags:
        - autofs
        - molecule-idempotence-notest
