---

- name: Database Server Installation
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - arvatosystems.ansible_oracle.oraswdb_install
    - arvatosystems.ansible_oracle.oraswdb_manage_patches
