---
- name: Oracle Grid Infrastructure / Restart installation & ASM Configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - arvatosystems.ansible_oracle.oraswgi_install
    - arvatosystems.ansible_oracle.oraswgi_manage_patches
    - arvatosystems.ansible_oracle.oraasm_manage_diskgroups
